{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertly.fullname" . }}
  labels:
    {{- include "alertly.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.keys.botToken }}: {{ required "secret.values.telegramBotToken is required when secret.create=true" .Values.secret.values.telegramBotToken | b64enc }}
  {{ .Values.secret.keys.webhookAuth }}: {{ required "secret.values.webhookAuthToken is required when secret.create=true" .Values.secret.values.webhookAuthToken | b64enc }}
  {{- with .Values.secret.values.alertmanagerUsername }}
  {{ $.Values.secret.keys.alertmanagerUsername }}: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.secret.values.alertmanagerPassword }}
  {{ $.Values.secret.keys.alertmanagerPassword }}: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.secret.values.alertmanagerToken }}
  {{ $.Values.secret.keys.alertmanagerToken }}: {{ . | b64enc }}
  {{- end }}
{{- end }}
